baseURL: "https://unofficialism.info"
canonifyurls: true
publishDir : "public"
title: "Yoichi Kawasaki"
paginate: 10
theme: PaperMod

enableEmoji : true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

# Jekyll-style date and slug from filename
# https://gohugo.io/getting-started/configuration/#configure-front-matter
frontmatter:
    date: [":filename", ":default", ":fileModTime"]

# Search output
# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
    home: [HTML,RSS,JSON]
    #home:
    #  - HTML
    #  - RSS
    #  - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Yoichi Kawasaki
    description: "Yoichi Kawasaki yokawasa.github.io"
    keywords: [Blog, Yoichi Kawasaki]
    author: Yoichi Kawasaki 
    # author: ["Me", "You"] # multiple authors
    images: ["profile.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShareButtons: [twitter,linkedin,reddit,facebook]
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true

    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "Thinking_Face_Emoji_large.png"
        favicon16x16: "Thinking_Face_Emoji_large.png"
        favicon32x32: "Thinking_Face_Emoji_large.png"
        apple_touch_icon: "Thinking_Face_Emoji_large.png"
        safari_pinned_tab: "Thinking_Face_Emoji_large.png"

    label:
        text: "unofficialism"
        # icon: Thinking_Face_Emoji_large.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "Yoichi Kawasaki"
        # subtitle: "Software Engineer, NoOps Practitioner"
        subtitle: "Software Engineer, NoOps Practitioner, loving 🧖 🍺 ⛺"
        imageUrl: "profile.jpg"
        imageWidth: 200
        imageHeight: 200
        imageTitle: my image
        #buttons:
        #  - name: posts
        #    url: posts
        #  - name: works
        #    url: works
        #  - name: slides
        #    url: https://speakerdeck.com/yokawasa
        #  - name: books
        #    url: "https://amzn.to/3J0OSgb"

    socialIcons:
        - name: twitter
          url: "https://twitter.com/yokawasa"
        - name: github
          url: "https://github.com/yokawasa"
        - name: linkedin
          url: "https://www.linkedin.com/in/yokawasa/"
        - name: rss
          url: "index.xml"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/yokawasa/yokawasa.github.io/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - name: about
          url: about
          weight: 5
        - identifier: posts
          name: posts
          url: posts
          weight: 10
        - name: works
          url: works
          weight: 15
        - name: search
          url: search/
          weight: 20 
        - identifier: tags
          name: tags
          url: tags/
          weight: 25

